name: 'Setup Nim compiler and tools'
description: 'Download and install the selected Nim nightly build'

inputs:
  version:
    description: 'Which nightly-tracked branch should be fetched'
    required: true
    default: 'devel'
  path:
    description: 'The path which the compiler will be downloaded to'
    required: false
    default: 'nim'
  add-to-path:
    description: 'Whether the compiler should be added to PATH'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: 'Download the Nim compiler'
      shell: bash
      run: |
        '${{ github.action_path }}/setup.sh' -o '${{ inputs.path }}' '${{ inputs.version }}'

    - name: 'Enable annotations support'
      shell: bash
      run: echo '::add-matcher::${{ github.action_path }}/.github/nim.json'

    - name: 'Add the Nim compiler to PATH'
      shell: bash
      run: |
        add-path() {
          echo "$1" >> "$GITHUB_PATH"
          echo "Directory '$1' has been added to PATH."
        }

        real-path() {
          if [[ '${{ runner.os }}' == 'Windows' ]]; then
            cygpath -aw "$1"
          else
            python -c "import os; import sys; print(os.path.realpath(sys.argv[1]))" "$1"
          fi
        }

        if ${{ inputs.add-to-path }}; then
          path='${{ inputs.path }}'
          add-path "$(real-path "$path/bin")"
          add-path "$(real-path "$HOME/.nimble/bin")"
        else
          echo "This step was skipped per user request."
        fi

branding:
  icon: 'download-cloud'
  color: 'yellow'
